modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/Smallinger/Copper-Age-Backport/issues"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://github.com/Smallinger/Copper-Age-Backport"
logoFile="logo.png"
credits="${credits}"
authors="${mod_author}"
description='''${description}'''
[[mixins]]
config="copperagebackport.neoforge.mixins.json"
[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="${neoforge_loader_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
